version: "3.8"

services:
  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
